# Analyse des artistes les plus streamés sur Spotify de janvier à juillet 2026

## 1. Import des packages

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

## 2. Import du csv

In [ ]:
df = pd.read_csv("/content/Most Streamed Artists on Spotify (17_07_2026).csv", sep=',')

## 3. Explorer le Dataframe

In [ ]:
df.head(7)

,Artist,Sex,Country,Langugage,Primary Genre,Artist Type,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
0,Drake,Male,Canada,English,Hip-Hop,Solo,137492.1,94851.1,42640.9,53323.9
1,Taylor Swift,Female,United States,English,Pop,Solo,127861.0,126177.3,1683.8,113421.5
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,125899.8,82189.3,43710.5,48887.0
3,The Weeknd,Male,Canada,English,R&B,Solo,95703.2,77189.4,18513.8,51020.0
4,Justin Bieber,Male,Canada,English,Pop,Solo,78104.4,48316.2,29788.2,29638.3
5,Ariana Grande,Female,United States,English,Pop,Solo,68298.9,57097.5,11201.4,41615.5
6,Travis Scott,Male,United States,English,Hip-Hop,Solo,65349.7,35338.7,30027.0,25309.9

In [ ]:
df.shape

(500, 10)

In [ ]:
df.describe()

,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions)
count,500.000000,497.000000,468.000000,493.000000
mean,16817.610200,12215.024145,5001.377137,8442.593915
std,14845.197632,11842.628550,6021.629551,9605.072797
min,6972.000000,8.400000,0.400000,1.300000
25%,8768.175000,6568.500000,971.450000,2755.300000
50%,11923.250000,8772.200000,3367.850000,6592.700000
75%,18020.050000,13579.300000,6333.525000,10141.500000
max,137492.100000,126177.300000,43710.500000,113421.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Artist                         500 non-null    object
 1   Sex                            500 non-null    object
 2   Country                        500 non-null    object
 3   Langugage                      500 non-null    object
 4   Primary Genre                  500 non-null    object
 5    Artist Type                   500 non-null    object
 6   Total Streams (in millions)    500 non-null    float64
 7   Lead Streams (in millions)     497 non-null    float64
 8   Feature Streams (in millions)  468 non-null    float64
 9   Solo Streams (in millions)     493 non-null    float64
dtypes: float64(4), object(6)
memory usage: 39.2+ KB

In [ ]:
df.isna().sum()

Artist                            0
Sex                               0
Country                           0
Langugage                         0
Primary Genre                     0
 Artist Type                      0
Total Streams (in millions)       0
Lead Streams (in millions)        3
Feature Streams (in millions)    32
Solo Streams (in millions)        7
dtype: int64

In [ ]:
df['Artist'].nunique()

500

In [ ]:
df['Primary Genre'].nunique()

23

In [ ]:
df['Primary Genre'].value_counts()

Primary Genre
Hip-Hop             115
Pop                 102
Rock                 60
Reggaeton            43
R&B                  31
Latin                30
EDM                  22
Regional Mexican     19
K-Pop                11
Filmi                11
Country              10
Alternative           9
Sertanjeo             9
Metal                 8
Folk                  4
Soundtrack            3
Bachata               3
Soul                  3
Reggae                2
Afrobeats             2
Spoken Word           1
Children's Music      1
Nu Metal              1
Name: count, dtype: int64

## 4. Insights

In [ ]:
df['Sex'].value_counts()

Sex
Male      390
Female     88
Mixed      22
Name: count, dtype: int64

In [ ]:
df.groupby('Country')["Sex"].value_counts()

Country         Sex
Argentina       Male        6
                Female      3
Australia       Male        6
                Female      1
Austria         Male        1
                         ...
United Kingdom  Mixed       3
United States   Male      211
                Female     40
                Mixed      14
Venezuela       Male        1
Name: count, Length: 64, dtype: int64

In [ ]:
df.groupby('Artist')['Lead Streams (in millions)'].max().sort_values(ascending=False).head(3)

Artist
Taylor Swift    126177.3
Drake            94851.1
Bad Bunny        82189.3
Name: Lead Streams (in millions), dtype: float64

In [ ]:
df.groupby('Artist')['Solo Streams (in millions)'].max().sort_values(ascending=False).head(3)

Artist
Taylor Swift     113421.5
Drake             53323.9
Billie Eilish     51567.9
Name: Solo Streams (in millions), dtype: float64

In [ ]:
df.groupby('Artist')['Feature Streams (in millions)'].max().sort_values(ascending=False).head(3)

Artist
Bad Bunny       43710.5
Drake           42640.9
Travis Scott    30027.0
Name: Feature Streams (in millions), dtype: float64

## 5. Visualisation Power BI

Voir feuille PowerBI